### ISSUE TITLE
Richiesta: Check Campo Gravity Form

### ISSUE THREAD

**Issue by silenx** [mailrouter/Newsletter-for-Wordpress#1]
Salve,
volevo chiedervi se potete implementare la selezione di default del campo "Iscriviti alla newsletter" in Gravity Form.
Grazie.
Cordiali saluti

**Comment by morloi** [comment]
Salve, considerando anche l'avvento del GDPR, che richiede un'azione positiva e chiara del consenso, non penso valuteremo la selezione di default del campo: anche altrove, dove era possibile, abbiamo consigliato di non utilizzarla.
