### ISSUE TITLE
Creazione moduli form separati 

### ISSUE THREAD

**Issue by myfoxx** [mailrouter/Newsletter-for-Wordpress#3]
Nel caso si abbiano più gruppi di mailling list, ma non si voglia fare vedere l'elenco a tutti, sarebbe utile poter creare più form mail all'interno del plugin, cosi da poter includerli separatamente nelle pagine specifiche, e ovviamente tramite un imput file hidden specificare a quale gruppo fare l'iscrizione.

**Comment by bago** [comment]
Issue molto vecchio ma la versione [4.5.12](https://github.com/mailrouter/Newsletter-for-Wordpress/releases/tag/v4.5.12) appena pubblicata supporta la gestione di più moduli.
