### ISSUE TITLE
PHP 7.3 Warning strpos() deprecated

### ISSUE THREAD

**Issue by multiformeingegno** [mailrouter/Newsletter-for-Wordpress#5]
PHP 7.3 throws the warning:
`Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /plugin-update-checker/Puc/v4p5/Plugin/Package.php on line 167`

**Comment by bago** [comment]
This will require an update of the plugin-update-checker, in the next release:
https://github.com/YahnisElsts/plugin-update-checker/releases
