### ISSUE TITLE
PHP Deprecated:  Return type of NL4WP_Container::offsetGet($offset)

### ISSUE THREAD

**Issue by dopamigs84** [mailrouter/Newsletter-for-Wordpress#7]
PHP 8.1.19
PHP Deprecated:  Return type of NL4WP_Container::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /httpdocs/wp-content/plugins/Newsletter-for-Wordpress-4.5.9/includes/class-container.php

**Comment by socrates77** [comment]
I made a pull request for this error https://github.com/mailrouter/Newsletter-for-Wordpress/pull/8
@morloi @bago
